/* This file was generated by SableCC (http://www.sablecc.org/). */

package simpleAdder.analysis;

import java.util.*;
import simpleAdder.node.*;

public class ReversedDepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getEOF().apply(this);
        node.getPProgram().apply(this);
        outStart(node);
    }

    public void inASingleProgram(ASingleProgram node)
    {
        defaultIn(node);
    }

    public void outASingleProgram(ASingleProgram node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASingleProgram(ASingleProgram node)
    {
        inASingleProgram(node);
        if(node.getStatement() != null)
        {
            node.getStatement().apply(this);
        }
        outASingleProgram(node);
    }

    public void inASequenceProgram(ASequenceProgram node)
    {
        defaultIn(node);
    }

    public void outASequenceProgram(ASequenceProgram node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASequenceProgram(ASequenceProgram node)
    {
        inASequenceProgram(node);
        if(node.getStatement() != null)
        {
            node.getStatement().apply(this);
        }
        if(node.getProgram() != null)
        {
            node.getProgram().apply(this);
        }
        outASequenceProgram(node);
    }

    public void inAStatement(AStatement node)
    {
        defaultIn(node);
    }

    public void outAStatement(AStatement node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAStatement(AStatement node)
    {
        inAStatement(node);
        if(node.getSemi() != null)
        {
            node.getSemi().apply(this);
        }
        if(node.getRight() != null)
        {
            node.getRight().apply(this);
        }
        if(node.getPlus() != null)
        {
            node.getPlus().apply(this);
        }
        if(node.getLeft() != null)
        {
            node.getLeft().apply(this);
        }
        outAStatement(node);
    }
}
