/* This file was generated by SableCC (http://www.sablecc.org/). */

package xyzlex.parser;

import xyzlex.lexer.*;
import xyzlex.node.*;
import xyzlex.analysis.*;
import java.util.*;

import java.io.DataInputStream;
import java.io.BufferedInputStream;
import java.io.IOException;

@SuppressWarnings("nls")
public class Parser
{
    public final Analysis ignoredTokens = new AnalysisAdapter();

    protected ArrayList nodeList;

    private final Lexer lexer;
    private final ListIterator stack = new LinkedList().listIterator();
    private int last_pos;
    private int last_line;
    private Token last_token;
    private final TokenIndex converter = new TokenIndex();
    private final int[] action = new int[2];

    private final static int SHIFT = 0;
    private final static int REDUCE = 1;
    private final static int ACCEPT = 2;
    private final static int ERROR = 3;

    public Parser(@SuppressWarnings("hiding") Lexer lexer)
    {
        this.lexer = lexer;
    }

    @SuppressWarnings({"unchecked","unused"})
    private void push(int numstate, ArrayList listNode) throws ParserException, LexerException, IOException
    {
        this.nodeList = listNode;

        if(!this.stack.hasNext())
        {
            this.stack.add(new State(numstate, this.nodeList));
            return;
        }

        State s = (State) this.stack.next();
        s.state = numstate;
        s.nodes = this.nodeList;
    }

    private int goTo(int index)
    {
        int state = state();
        int low = 1;
        int high = gotoTable[index].length - 1;
        int value = gotoTable[index][0][1];

        while(low <= high)
        {
            int middle = (low + high) / 2;

            if(state < gotoTable[index][middle][0])
            {
                high = middle - 1;
            }
            else if(state > gotoTable[index][middle][0])
            {
                low = middle + 1;
            }
            else
            {
                value = gotoTable[index][middle][1];
                break;
            }
        }

        return value;
    }

    private int state()
    {
        State s = (State) this.stack.previous();
        this.stack.next();
        return s.state;
    }

    private ArrayList pop()
    {
        return ((State) this.stack.previous()).nodes;
    }

    private int index(Switchable token)
    {
        this.converter.index = -1;
        token.apply(this.converter);
        return this.converter.index;
    }

    @SuppressWarnings("unchecked")
    public Start parse() throws ParserException, LexerException, IOException
    {
        push(0, null);
        List<Node> ign = null;
        while(true)
        {
            while(index(this.lexer.peek()) == -1)
            {
                if(ign == null)
                {
                    ign = new LinkedList<Node>();
                }

                ign.add(this.lexer.next());
            }

            if(ign != null)
            {
                this.ignoredTokens.setIn(this.lexer.peek(), ign);
                ign = null;
            }

            this.last_pos = this.lexer.peek().getPos();
            this.last_line = this.lexer.peek().getLine();
            this.last_token = this.lexer.peek();

            int index = index(this.lexer.peek());
            this.action[0] = Parser.actionTable[state()][0][1];
            this.action[1] = Parser.actionTable[state()][0][2];

            int low = 1;
            int high = Parser.actionTable[state()].length - 1;

            while(low <= high)
            {
                int middle = (low + high) / 2;

                if(index < Parser.actionTable[state()][middle][0])
                {
                    high = middle - 1;
                }
                else if(index > Parser.actionTable[state()][middle][0])
                {
                    low = middle + 1;
                }
                else
                {
                    this.action[0] = Parser.actionTable[state()][middle][1];
                    this.action[1] = Parser.actionTable[state()][middle][2];
                    break;
                }
            }

            switch(this.action[0])
            {
                case SHIFT:
		    {
		        ArrayList list = new ArrayList();
		        list.add(this.lexer.next());
                        push(this.action[1], list);
                    }
		    break;
                case REDUCE:
                    switch(this.action[1])
                    {
                    case 0: /* reduce AAclassprogram1Program */
		    {
			ArrayList list = new0();
			push(goTo(0), list);
		    }
		    break;
                    case 1: /* reduce AAclassprogram2Program */
		    {
			ArrayList list = new1();
			push(goTo(0), list);
		    }
		    break;
                    case 2: /* reduce ABodyProgram */
		    {
			ArrayList list = new2();
			push(goTo(0), list);
		    }
		    break;
                    case 3: /* reduce AMainClass */
		    {
			ArrayList list = new3();
			push(goTo(1), list);
		    }
		    break;
                    case 4: /* reduce AAclassdecl1ClassDecl */
		    {
			ArrayList list = new4();
			push(goTo(2), list);
		    }
		    break;
                    case 5: /* reduce AAclassdecl2ClassDecl */
		    {
			ArrayList list = new5();
			push(goTo(2), list);
		    }
		    break;
                    case 6: /* reduce AAclassdecl3ClassDecl */
		    {
			ArrayList list = new6();
			push(goTo(2), list);
		    }
		    break;
                    case 7: /* reduce AAclassdecl4ClassDecl */
		    {
			ArrayList list = new7();
			push(goTo(2), list);
		    }
		    break;
                    case 8: /* reduce AAclassdecl5ClassDecl */
		    {
			ArrayList list = new8();
			push(goTo(2), list);
		    }
		    break;
                    case 9: /* reduce AAclassdecl6ClassDecl */
		    {
			ArrayList list = new9();
			push(goTo(2), list);
		    }
		    break;
                    case 10: /* reduce AAclassdecl7ClassDecl */
		    {
			ArrayList list = new10();
			push(goTo(2), list);
		    }
		    break;
                    case 11: /* reduce AAclassdecl8ClassDecl */
		    {
			ArrayList list = new11();
			push(goTo(2), list);
		    }
		    break;
                    case 12: /* reduce AExtendsClause */
		    {
			ArrayList list = new12();
			push(goTo(3), list);
		    }
		    break;
                    case 13: /* reduce AMethodDecl */
		    {
			ArrayList list = new13();
			push(goTo(4), list);
		    }
		    break;
                    case 14: /* reduce AAformallist1FormalList */
		    {
			ArrayList list = new14();
			push(goTo(5), list);
		    }
		    break;
                    case 15: /* reduce AAformallist2FormalList */
		    {
			ArrayList list = new15();
			push(goTo(5), list);
		    }
		    break;
                    case 16: /* reduce AArg */
		    {
			ArrayList list = new16();
			push(goTo(6), list);
		    }
		    break;
                    case 17: /* reduce AFormalRest */
		    {
			ArrayList list = new17();
			push(goTo(7), list);
		    }
		    break;
                    case 18: /* reduce APreDecl */
		    {
			ArrayList list = new18();
			push(goTo(8), list);
		    }
		    break;
                    case 19: /* reduce APostDecl */
		    {
			ArrayList list = new19();
			push(goTo(9), list);
		    }
		    break;
                    case 20: /* reduce AAbody1Body */
		    {
			ArrayList list = new20();
			push(goTo(10), list);
		    }
		    break;
                    case 21: /* reduce AAbody2Body */
		    {
			ArrayList list = new21();
			push(goTo(10), list);
		    }
		    break;
                    case 22: /* reduce AAbody3Body */
		    {
			ArrayList list = new22();
			push(goTo(10), list);
		    }
		    break;
                    case 23: /* reduce AAbody4Body */
		    {
			ArrayList list = new23();
			push(goTo(10), list);
		    }
		    break;
                    case 24: /* reduce AVarDecl */
		    {
			ArrayList list = new24();
			push(goTo(11), list);
		    }
		    break;
                    case 25: /* reduce AIntArrayType */
		    {
			ArrayList list = new25();
			push(goTo(12), list);
		    }
		    break;
                    case 26: /* reduce ARealArrayType */
		    {
			ArrayList list = new26();
			push(goTo(12), list);
		    }
		    break;
                    case 27: /* reduce ABooleanType */
		    {
			ArrayList list = new27();
			push(goTo(12), list);
		    }
		    break;
                    case 28: /* reduce AIntType */
		    {
			ArrayList list = new28();
			push(goTo(12), list);
		    }
		    break;
                    case 29: /* reduce ARealType */
		    {
			ArrayList list = new29();
			push(goTo(12), list);
		    }
		    break;
                    case 30: /* reduce AClassType */
		    {
			ArrayList list = new30();
			push(goTo(12), list);
		    }
		    break;
                    case 31: /* reduce AAblockstate1State */
		    {
			ArrayList list = new31();
			push(goTo(13), list);
		    }
		    break;
                    case 32: /* reduce AAblockstate2State */
		    {
			ArrayList list = new32();
			push(goTo(13), list);
		    }
		    break;
                    case 33: /* reduce AIfState */
		    {
			ArrayList list = new33();
			push(goTo(13), list);
		    }
		    break;
                    case 34: /* reduce AWhileState */
		    {
			ArrayList list = new34();
			push(goTo(13), list);
		    }
		    break;
                    case 35: /* reduce APrintState */
		    {
			ArrayList list = new35();
			push(goTo(13), list);
		    }
		    break;
                    case 36: /* reduce AAassignstate1State */
		    {
			ArrayList list = new36();
			push(goTo(13), list);
		    }
		    break;
                    case 37: /* reduce AAassignstate2State */
		    {
			ArrayList list = new37();
			push(goTo(13), list);
		    }
		    break;
                    case 38: /* reduce AArrayIndex */
		    {
			ArrayList list = new38();
			push(goTo(14), list);
		    }
		    break;
                    case 39: /* reduce AOrOprExp */
		    {
			ArrayList list = new39();
			push(goTo(15), list);
		    }
		    break;
                    case 40: /* reduce ASingleExp */
		    {
			ArrayList list = new40();
			push(goTo(15), list);
		    }
		    break;
                    case 41: /* reduce AAndOprExp1 */
		    {
			ArrayList list = new41();
			push(goTo(16), list);
		    }
		    break;
                    case 42: /* reduce ASingleExp1 */
		    {
			ArrayList list = new42();
			push(goTo(16), list);
		    }
		    break;
                    case 43: /* reduce ANotOprExp2 */
		    {
			ArrayList list = new43();
			push(goTo(17), list);
		    }
		    break;
                    case 44: /* reduce ASingleExp2 */
		    {
			ArrayList list = new44();
			push(goTo(17), list);
		    }
		    break;
                    case 45: /* reduce AGreaterOprExp3 */
		    {
			ArrayList list = new45();
			push(goTo(18), list);
		    }
		    break;
                    case 46: /* reduce ALessOprExp3 */
		    {
			ArrayList list = new46();
			push(goTo(18), list);
		    }
		    break;
                    case 47: /* reduce ASingleExp3 */
		    {
			ArrayList list = new47();
			push(goTo(18), list);
		    }
		    break;
                    case 48: /* reduce APlusOprExp4 */
		    {
			ArrayList list = new48();
			push(goTo(19), list);
		    }
		    break;
                    case 49: /* reduce AMinusOprExp4 */
		    {
			ArrayList list = new49();
			push(goTo(19), list);
		    }
		    break;
                    case 50: /* reduce ASingleExp4 */
		    {
			ArrayList list = new50();
			push(goTo(19), list);
		    }
		    break;
                    case 51: /* reduce AMultiplyOprExp5 */
		    {
			ArrayList list = new51();
			push(goTo(20), list);
		    }
		    break;
                    case 52: /* reduce ADivideOprExp5 */
		    {
			ArrayList list = new52();
			push(goTo(20), list);
		    }
		    break;
                    case 53: /* reduce ASingleExp5 */
		    {
			ArrayList list = new53();
			push(goTo(20), list);
		    }
		    break;
                    case 54: /* reduce AIntLtTerm */
		    {
			ArrayList list = new54();
			push(goTo(21), list);
		    }
		    break;
                    case 55: /* reduce ARealLtTerm */
		    {
			ArrayList list = new55();
			push(goTo(21), list);
		    }
		    break;
                    case 56: /* reduce ATrueLtTerm */
		    {
			ArrayList list = new56();
			push(goTo(21), list);
		    }
		    break;
                    case 57: /* reduce AFalseLtTerm */
		    {
			ArrayList list = new57();
			push(goTo(21), list);
		    }
		    break;
                    case 58: /* reduce AVarTerm */
		    {
			ArrayList list = new58();
			push(goTo(21), list);
		    }
		    break;
                    case 59: /* reduce AThisTerm */
		    {
			ArrayList list = new59();
			push(goTo(21), list);
		    }
		    break;
                    case 60: /* reduce ASubExpTerm */
		    {
			ArrayList list = new60();
			push(goTo(21), list);
		    }
		    break;
                    case 61: /* reduce AArraySubTerm */
		    {
			ArrayList list = new61();
			push(goTo(21), list);
		    }
		    break;
                    case 62: /* reduce AArrayLengthTerm */
		    {
			ArrayList list = new62();
			push(goTo(21), list);
		    }
		    break;
                    case 63: /* reduce AAmemfuncterm1Term */
		    {
			ArrayList list = new63();
			push(goTo(21), list);
		    }
		    break;
                    case 64: /* reduce AAmemfuncterm2Term */
		    {
			ArrayList list = new64();
			push(goTo(21), list);
		    }
		    break;
                    case 65: /* reduce ANewIntArTerm */
		    {
			ArrayList list = new65();
			push(goTo(21), list);
		    }
		    break;
                    case 66: /* reduce ANewRealArTerm */
		    {
			ArrayList list = new66();
			push(goTo(21), list);
		    }
		    break;
                    case 67: /* reduce ANewObjectTerm */
		    {
			ArrayList list = new67();
			push(goTo(21), list);
		    }
		    break;
                    case 68: /* reduce ACommaSepExpList */
		    {
			ArrayList list = new68();
			push(goTo(22), list);
		    }
		    break;
                    case 69: /* reduce ASingleExpList */
		    {
			ArrayList list = new69();
			push(goTo(22), list);
		    }
		    break;
                    case 70: /* reduce ATerminal$ClassDecl */
		    {
			ArrayList list = new70();
			push(goTo(23), list);
		    }
		    break;
                    case 71: /* reduce ANonTerminal$ClassDecl */
		    {
			ArrayList list = new71();
			push(goTo(23), list);
		    }
		    break;
                    case 72: /* reduce ATerminal$VarDecl */
		    {
			ArrayList list = new72();
			push(goTo(24), list);
		    }
		    break;
                    case 73: /* reduce ANonTerminal$VarDecl */
		    {
			ArrayList list = new73();
			push(goTo(24), list);
		    }
		    break;
                    case 74: /* reduce ATerminal$MethodDecl */
		    {
			ArrayList list = new74();
			push(goTo(25), list);
		    }
		    break;
                    case 75: /* reduce ANonTerminal$MethodDecl */
		    {
			ArrayList list = new75();
			push(goTo(25), list);
		    }
		    break;
                    case 76: /* reduce ATerminal$FormalRest */
		    {
			ArrayList list = new76();
			push(goTo(26), list);
		    }
		    break;
                    case 77: /* reduce ANonTerminal$FormalRest */
		    {
			ArrayList list = new77();
			push(goTo(26), list);
		    }
		    break;
                    case 78: /* reduce ATerminal$State */
		    {
			ArrayList list = new78();
			push(goTo(27), list);
		    }
		    break;
                    case 79: /* reduce ANonTerminal$State */
		    {
			ArrayList list = new79();
			push(goTo(27), list);
		    }
		    break;
                    }
                    break;
                case ACCEPT:
                    {
                        EOF node2 = (EOF) this.lexer.next();
                        PProgram node1 = (PProgram) pop().get(0);
                        Start node = new Start(node1, node2);
                        return node;
                    }
                case ERROR:
                    throw new ParserException(this.last_token,
                        "[" + this.last_line + "," + this.last_pos + "] " +
                        Parser.errorMessages[Parser.errors[this.action[1]]]);
            }
        }
    }



    @SuppressWarnings("unchecked")
    ArrayList new0() /* reduce AAclassprogram1Program */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PProgram pprogramNode1;
        {
            // Block
        PMainClass pmainclassNode2;
        LinkedList listNode3 = new LinkedList();
        pmainclassNode2 = (PMainClass)nodeArrayList1.get(0);
        {
            // Block
        }

        pprogramNode1 = new AClassProgram(pmainclassNode2, listNode3);
        }
	nodeList.add(pprogramNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new1() /* reduce AAclassprogram2Program */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PProgram pprogramNode1;
        {
            // Block
        PMainClass pmainclassNode2;
        LinkedList listNode4 = new LinkedList();
        pmainclassNode2 = (PMainClass)nodeArrayList1.get(0);
        {
            // Block
        LinkedList listNode3 = new LinkedList();
        listNode3 = (LinkedList)nodeArrayList2.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pprogramNode1 = new AClassProgram(pmainclassNode2, listNode4);
        }
	nodeList.add(pprogramNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new2() /* reduce ABodyProgram */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PProgram pprogramNode1;
        {
            // Block
        PBody pbodyNode2;
        pbodyNode2 = (PBody)nodeArrayList1.get(0);

        pprogramNode1 = new ABodyProgram(pbodyNode2);
        }
	nodeList.add(pprogramNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new3() /* reduce AMainClass */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList13 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList12 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList11 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList10 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList9 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList8 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PMainClass pmainclassNode1;
        {
            // Block
        TId tidNode2;
        PBody pbodyNode3;
        tidNode2 = (TId)nodeArrayList2.get(0);
        pbodyNode3 = (PBody)nodeArrayList11.get(0);

        pmainclassNode1 = new AMainClass(tidNode2, pbodyNode3);
        }
	nodeList.add(pmainclassNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new4() /* reduce AAclassdecl1ClassDecl */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PClassDecl pclassdeclNode1;
        {
            // Block
        TId tidNode2;
        @SuppressWarnings("unused") Object nullNode3 = null;
        LinkedList listNode4 = new LinkedList();
        LinkedList listNode5 = new LinkedList();
        tidNode2 = (TId)nodeArrayList2.get(0);
        {
            // Block
        }
        {
            // Block
        }

        pclassdeclNode1 = new AClassDecl(tidNode2, null, listNode4, listNode5);
        }
	nodeList.add(pclassdeclNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new5() /* reduce AAclassdecl2ClassDecl */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PClassDecl pclassdeclNode1;
        {
            // Block
        TId tidNode2;
        PExtendsClause pextendsclauseNode3;
        LinkedList listNode4 = new LinkedList();
        LinkedList listNode5 = new LinkedList();
        tidNode2 = (TId)nodeArrayList2.get(0);
        pextendsclauseNode3 = (PExtendsClause)nodeArrayList3.get(0);
        {
            // Block
        }
        {
            // Block
        }

        pclassdeclNode1 = new AClassDecl(tidNode2, pextendsclauseNode3, listNode4, listNode5);
        }
	nodeList.add(pclassdeclNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new6() /* reduce AAclassdecl3ClassDecl */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PClassDecl pclassdeclNode1;
        {
            // Block
        TId tidNode2;
        @SuppressWarnings("unused") Object nullNode3 = null;
        LinkedList listNode5 = new LinkedList();
        LinkedList listNode6 = new LinkedList();
        tidNode2 = (TId)nodeArrayList2.get(0);
        {
            // Block
        LinkedList listNode4 = new LinkedList();
        listNode4 = (LinkedList)nodeArrayList4.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }
        {
            // Block
        }

        pclassdeclNode1 = new AClassDecl(tidNode2, null, listNode5, listNode6);
        }
	nodeList.add(pclassdeclNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new7() /* reduce AAclassdecl4ClassDecl */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PClassDecl pclassdeclNode1;
        {
            // Block
        TId tidNode2;
        PExtendsClause pextendsclauseNode3;
        LinkedList listNode5 = new LinkedList();
        LinkedList listNode6 = new LinkedList();
        tidNode2 = (TId)nodeArrayList2.get(0);
        pextendsclauseNode3 = (PExtendsClause)nodeArrayList3.get(0);
        {
            // Block
        LinkedList listNode4 = new LinkedList();
        listNode4 = (LinkedList)nodeArrayList5.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }
        {
            // Block
        }

        pclassdeclNode1 = new AClassDecl(tidNode2, pextendsclauseNode3, listNode5, listNode6);
        }
	nodeList.add(pclassdeclNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new8() /* reduce AAclassdecl5ClassDecl */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PClassDecl pclassdeclNode1;
        {
            // Block
        TId tidNode2;
        @SuppressWarnings("unused") Object nullNode3 = null;
        LinkedList listNode4 = new LinkedList();
        LinkedList listNode6 = new LinkedList();
        tidNode2 = (TId)nodeArrayList2.get(0);
        {
            // Block
        }
        {
            // Block
        LinkedList listNode5 = new LinkedList();
        listNode5 = (LinkedList)nodeArrayList4.get(0);
	if(listNode5 != null)
	{
	  listNode6.addAll(listNode5);
	}
        }

        pclassdeclNode1 = new AClassDecl(tidNode2, null, listNode4, listNode6);
        }
	nodeList.add(pclassdeclNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new9() /* reduce AAclassdecl6ClassDecl */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PClassDecl pclassdeclNode1;
        {
            // Block
        TId tidNode2;
        PExtendsClause pextendsclauseNode3;
        LinkedList listNode4 = new LinkedList();
        LinkedList listNode6 = new LinkedList();
        tidNode2 = (TId)nodeArrayList2.get(0);
        pextendsclauseNode3 = (PExtendsClause)nodeArrayList3.get(0);
        {
            // Block
        }
        {
            // Block
        LinkedList listNode5 = new LinkedList();
        listNode5 = (LinkedList)nodeArrayList5.get(0);
	if(listNode5 != null)
	{
	  listNode6.addAll(listNode5);
	}
        }

        pclassdeclNode1 = new AClassDecl(tidNode2, pextendsclauseNode3, listNode4, listNode6);
        }
	nodeList.add(pclassdeclNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new10() /* reduce AAclassdecl7ClassDecl */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PClassDecl pclassdeclNode1;
        {
            // Block
        TId tidNode2;
        @SuppressWarnings("unused") Object nullNode3 = null;
        LinkedList listNode5 = new LinkedList();
        LinkedList listNode7 = new LinkedList();
        tidNode2 = (TId)nodeArrayList2.get(0);
        {
            // Block
        LinkedList listNode4 = new LinkedList();
        listNode4 = (LinkedList)nodeArrayList4.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }
        {
            // Block
        LinkedList listNode6 = new LinkedList();
        listNode6 = (LinkedList)nodeArrayList5.get(0);
	if(listNode6 != null)
	{
	  listNode7.addAll(listNode6);
	}
        }

        pclassdeclNode1 = new AClassDecl(tidNode2, null, listNode5, listNode7);
        }
	nodeList.add(pclassdeclNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new11() /* reduce AAclassdecl8ClassDecl */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PClassDecl pclassdeclNode1;
        {
            // Block
        TId tidNode2;
        PExtendsClause pextendsclauseNode3;
        LinkedList listNode5 = new LinkedList();
        LinkedList listNode7 = new LinkedList();
        tidNode2 = (TId)nodeArrayList2.get(0);
        pextendsclauseNode3 = (PExtendsClause)nodeArrayList3.get(0);
        {
            // Block
        LinkedList listNode4 = new LinkedList();
        listNode4 = (LinkedList)nodeArrayList5.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }
        {
            // Block
        LinkedList listNode6 = new LinkedList();
        listNode6 = (LinkedList)nodeArrayList6.get(0);
	if(listNode6 != null)
	{
	  listNode7.addAll(listNode6);
	}
        }

        pclassdeclNode1 = new AClassDecl(tidNode2, pextendsclauseNode3, listNode5, listNode7);
        }
	nodeList.add(pclassdeclNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new12() /* reduce AExtendsClause */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExtendsClause pextendsclauseNode1;
        {
            // Block
        TId tidNode2;
        tidNode2 = (TId)nodeArrayList2.get(0);

        pextendsclauseNode1 = new AExtendsClause(tidNode2);
        }
	nodeList.add(pextendsclauseNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new13() /* reduce AMethodDecl */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList14 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList13 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList12 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList11 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList10 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList9 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList8 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PMethodDecl pmethoddeclNode1;
        {
            // Block
        PType ptypeNode2;
        TId tidNode3;
        LinkedList listNode5 = new LinkedList();
        PPreDecl ppredeclNode6;
        PPostDecl ppostdeclNode7;
        PBody pbodyNode8;
        PExp pexpNode9;
        ptypeNode2 = (PType)nodeArrayList2.get(0);
        tidNode3 = (TId)nodeArrayList3.get(0);
        {
            // Block
        LinkedList listNode4 = new LinkedList();
        listNode4 = (LinkedList)nodeArrayList5.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }
        ppredeclNode6 = (PPreDecl)nodeArrayList8.get(0);
        ppostdeclNode7 = (PPostDecl)nodeArrayList9.get(0);
        pbodyNode8 = (PBody)nodeArrayList10.get(0);
        pexpNode9 = (PExp)nodeArrayList12.get(0);

        pmethoddeclNode1 = new AMethodDecl(ptypeNode2, tidNode3, listNode5, ppredeclNode6, ppostdeclNode7, pbodyNode8, pexpNode9);
        }
	nodeList.add(pmethoddeclNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new14() /* reduce AAformallist1FormalList */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode2 = new LinkedList();
        {
            // Block
        PArg pargNode1;
        pargNode1 = (PArg)nodeArrayList1.get(0);
	if(pargNode1 != null)
	{
	  listNode2.add(pargNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new15() /* reduce AAformallist2FormalList */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        PArg pargNode1;
        LinkedList listNode2 = new LinkedList();
        pargNode1 = (PArg)nodeArrayList1.get(0);
        listNode2 = (LinkedList)nodeArrayList2.get(0);
	if(pargNode1 != null)
	{
	  listNode3.add(pargNode1);
	}
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new16() /* reduce AArg */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PArg pargNode1;
        {
            // Block
        PType ptypeNode2;
        TId tidNode3;
        ptypeNode2 = (PType)nodeArrayList1.get(0);
        tidNode3 = (TId)nodeArrayList2.get(0);

        pargNode1 = new AArg(ptypeNode2, tidNode3);
        }
	nodeList.add(pargNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new17() /* reduce AFormalRest */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PArg pargNode1;
        {
            // Block
        PType ptypeNode2;
        TId tidNode3;
        ptypeNode2 = (PType)nodeArrayList2.get(0);
        tidNode3 = (TId)nodeArrayList3.get(0);

        pargNode1 = new AArg(ptypeNode2, tidNode3);
        }
	nodeList.add(pargNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new18() /* reduce APreDecl */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PPreDecl ppredeclNode1;
        {
            // Block
        TPre tpreNode2;
        PExp pexpNode3;
        tpreNode2 = (TPre)nodeArrayList1.get(0);
        pexpNode3 = (PExp)nodeArrayList3.get(0);

        ppredeclNode1 = new APreDecl(tpreNode2, pexpNode3);
        }
	nodeList.add(ppredeclNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new19() /* reduce APostDecl */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PPostDecl ppostdeclNode1;
        {
            // Block
        TPost tpostNode2;
        PExp pexpNode3;
        tpostNode2 = (TPost)nodeArrayList1.get(0);
        pexpNode3 = (PExp)nodeArrayList3.get(0);

        ppostdeclNode1 = new APostDecl(tpostNode2, pexpNode3);
        }
	nodeList.add(ppostdeclNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new20() /* reduce AAbody1Body */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        PBody pbodyNode1;
        {
            // Block
        LinkedList listNode2 = new LinkedList();
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        }
        {
            // Block
        }

        pbodyNode1 = new ABody(listNode2, listNode3);
        }
	nodeList.add(pbodyNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new21() /* reduce AAbody2Body */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PBody pbodyNode1;
        {
            // Block
        LinkedList listNode3 = new LinkedList();
        LinkedList listNode4 = new LinkedList();
        {
            // Block
        LinkedList listNode2 = new LinkedList();
        listNode2 = (LinkedList)nodeArrayList1.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }
        {
            // Block
        }

        pbodyNode1 = new ABody(listNode3, listNode4);
        }
	nodeList.add(pbodyNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new22() /* reduce AAbody3Body */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PBody pbodyNode1;
        {
            // Block
        LinkedList listNode2 = new LinkedList();
        LinkedList listNode4 = new LinkedList();
        {
            // Block
        }
        {
            // Block
        LinkedList listNode3 = new LinkedList();
        listNode3 = (LinkedList)nodeArrayList1.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pbodyNode1 = new ABody(listNode2, listNode4);
        }
	nodeList.add(pbodyNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new23() /* reduce AAbody4Body */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PBody pbodyNode1;
        {
            // Block
        LinkedList listNode3 = new LinkedList();
        LinkedList listNode5 = new LinkedList();
        {
            // Block
        LinkedList listNode2 = new LinkedList();
        listNode2 = (LinkedList)nodeArrayList1.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }
        {
            // Block
        LinkedList listNode4 = new LinkedList();
        listNode4 = (LinkedList)nodeArrayList2.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }

        pbodyNode1 = new ABody(listNode3, listNode5);
        }
	nodeList.add(pbodyNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new24() /* reduce AVarDecl */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PVarDecl pvardeclNode1;
        {
            // Block
        PType ptypeNode2;
        TId tidNode3;
        ptypeNode2 = (PType)nodeArrayList1.get(0);
        tidNode3 = (TId)nodeArrayList2.get(0);

        pvardeclNode1 = new AVarDecl(ptypeNode2, tidNode3);
        }
	nodeList.add(pvardeclNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new25() /* reduce AIntArrayType */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PType ptypeNode1;
        {
            // Block
        TInt tintNode2;
        TLSq tlsqNode3;
        TRSq trsqNode4;
        tintNode2 = (TInt)nodeArrayList1.get(0);
        tlsqNode3 = (TLSq)nodeArrayList2.get(0);
        trsqNode4 = (TRSq)nodeArrayList3.get(0);

        ptypeNode1 = new AIntArrayType(tintNode2, tlsqNode3, trsqNode4);
        }
	nodeList.add(ptypeNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new26() /* reduce ARealArrayType */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PType ptypeNode1;
        {
            // Block
        TReal trealNode2;
        TLSq tlsqNode3;
        TRSq trsqNode4;
        trealNode2 = (TReal)nodeArrayList1.get(0);
        tlsqNode3 = (TLSq)nodeArrayList2.get(0);
        trsqNode4 = (TRSq)nodeArrayList3.get(0);

        ptypeNode1 = new ARealArrayType(trealNode2, tlsqNode3, trsqNode4);
        }
	nodeList.add(ptypeNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new27() /* reduce ABooleanType */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PType ptypeNode1;
        {
            // Block
        TBoolean tbooleanNode2;
        tbooleanNode2 = (TBoolean)nodeArrayList1.get(0);

        ptypeNode1 = new ABooleanType(tbooleanNode2);
        }
	nodeList.add(ptypeNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new28() /* reduce AIntType */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PType ptypeNode1;
        {
            // Block
        TInt tintNode2;
        tintNode2 = (TInt)nodeArrayList1.get(0);

        ptypeNode1 = new AIntType(tintNode2);
        }
	nodeList.add(ptypeNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new29() /* reduce ARealType */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PType ptypeNode1;
        {
            // Block
        TReal trealNode2;
        trealNode2 = (TReal)nodeArrayList1.get(0);

        ptypeNode1 = new ARealType(trealNode2);
        }
	nodeList.add(ptypeNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new30() /* reduce AClassType */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PType ptypeNode1;
        {
            // Block
        TId tidNode2;
        tidNode2 = (TId)nodeArrayList1.get(0);

        ptypeNode1 = new AClassType(tidNode2);
        }
	nodeList.add(ptypeNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new31() /* reduce AAblockstate1State */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PState pstateNode1;
        {
            // Block
        LinkedList listNode2 = new LinkedList();
        {
            // Block
        }

        pstateNode1 = new ABlockState(listNode2);
        }
	nodeList.add(pstateNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new32() /* reduce AAblockstate2State */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PState pstateNode1;
        {
            // Block
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        LinkedList listNode2 = new LinkedList();
        listNode2 = (LinkedList)nodeArrayList2.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }

        pstateNode1 = new ABlockState(listNode3);
        }
	nodeList.add(pstateNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new33() /* reduce AIfState */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PState pstateNode1;
        {
            // Block
        PExp pexpNode2;
        PState pstateNode3;
        PState pstateNode4;
        pexpNode2 = (PExp)nodeArrayList3.get(0);
        pstateNode3 = (PState)nodeArrayList5.get(0);
        pstateNode4 = (PState)nodeArrayList7.get(0);

        pstateNode1 = new AIfState(pexpNode2, pstateNode3, pstateNode4);
        }
	nodeList.add(pstateNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new34() /* reduce AWhileState */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PState pstateNode1;
        {
            // Block
        PExp pexpNode2;
        PState pstateNode3;
        pexpNode2 = (PExp)nodeArrayList3.get(0);
        pstateNode3 = (PState)nodeArrayList5.get(0);

        pstateNode1 = new AWhileState(pexpNode2, pstateNode3);
        }
	nodeList.add(pstateNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new35() /* reduce APrintState */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PState pstateNode1;
        {
            // Block
        PExp pexpNode2;
        pexpNode2 = (PExp)nodeArrayList3.get(0);

        pstateNode1 = new APrintState(pexpNode2);
        }
	nodeList.add(pstateNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new36() /* reduce AAassignstate1State */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PState pstateNode1;
        {
            // Block
        TId tidNode2;
        @SuppressWarnings("unused") Object nullNode3 = null;
        PExp pexpNode4;
        tidNode2 = (TId)nodeArrayList1.get(0);
        pexpNode4 = (PExp)nodeArrayList3.get(0);

        pstateNode1 = new AAssignState(tidNode2, null, pexpNode4);
        }
	nodeList.add(pstateNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new37() /* reduce AAassignstate2State */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PState pstateNode1;
        {
            // Block
        TId tidNode2;
        PExp pexpNode3;
        PExp pexpNode4;
        tidNode2 = (TId)nodeArrayList1.get(0);
        pexpNode3 = (PExp)nodeArrayList2.get(0);
        pexpNode4 = (PExp)nodeArrayList4.get(0);

        pstateNode1 = new AAssignState(tidNode2, pexpNode3, pexpNode4);
        }
	nodeList.add(pstateNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new38() /* reduce AArrayIndex */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        pexpNode1 = (PExp)nodeArrayList2.get(0);
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new39() /* reduce AOrOprExp */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        TOrOpr toroprNode2;
        PExp pexpNode3;
        PExp pexpNode4;
        toroprNode2 = (TOrOpr)nodeArrayList2.get(0);
        pexpNode3 = (PExp)nodeArrayList1.get(0);
        pexpNode4 = (PExp)nodeArrayList3.get(0);

        pexpNode1 = new AOrOprExp(toroprNode2, pexpNode3, pexpNode4);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new40() /* reduce ASingleExp */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        pexpNode1 = (PExp)nodeArrayList1.get(0);
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new41() /* reduce AAndOprExp1 */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        TAndOpr tandoprNode2;
        PExp pexpNode3;
        PExp pexpNode4;
        tandoprNode2 = (TAndOpr)nodeArrayList2.get(0);
        pexpNode3 = (PExp)nodeArrayList1.get(0);
        pexpNode4 = (PExp)nodeArrayList3.get(0);

        pexpNode1 = new AAndOprExp(tandoprNode2, pexpNode3, pexpNode4);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new42() /* reduce ASingleExp1 */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        pexpNode1 = (PExp)nodeArrayList1.get(0);
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new43() /* reduce ANotOprExp2 */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        TNotOpr tnotoprNode2;
        PExp pexpNode3;
        tnotoprNode2 = (TNotOpr)nodeArrayList1.get(0);
        pexpNode3 = (PExp)nodeArrayList2.get(0);

        pexpNode1 = new ANotOprExp(tnotoprNode2, pexpNode3);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new44() /* reduce ASingleExp2 */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        pexpNode1 = (PExp)nodeArrayList1.get(0);
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new45() /* reduce AGreaterOprExp3 */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        TGreaterOpr tgreateroprNode2;
        PExp pexpNode3;
        PExp pexpNode4;
        tgreateroprNode2 = (TGreaterOpr)nodeArrayList2.get(0);
        pexpNode3 = (PExp)nodeArrayList1.get(0);
        pexpNode4 = (PExp)nodeArrayList3.get(0);

        pexpNode1 = new AGreaterOprExp(tgreateroprNode2, pexpNode3, pexpNode4);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new46() /* reduce ALessOprExp3 */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        TLessOpr tlessoprNode2;
        PExp pexpNode3;
        PExp pexpNode4;
        tlessoprNode2 = (TLessOpr)nodeArrayList2.get(0);
        pexpNode3 = (PExp)nodeArrayList1.get(0);
        pexpNode4 = (PExp)nodeArrayList3.get(0);

        pexpNode1 = new ALessOprExp(tlessoprNode2, pexpNode3, pexpNode4);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new47() /* reduce ASingleExp3 */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        pexpNode1 = (PExp)nodeArrayList1.get(0);
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new48() /* reduce APlusOprExp4 */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        TPlusOpr tplusoprNode2;
        PExp pexpNode3;
        PExp pexpNode4;
        tplusoprNode2 = (TPlusOpr)nodeArrayList2.get(0);
        pexpNode3 = (PExp)nodeArrayList1.get(0);
        pexpNode4 = (PExp)nodeArrayList3.get(0);

        pexpNode1 = new APlusOprExp(tplusoprNode2, pexpNode3, pexpNode4);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new49() /* reduce AMinusOprExp4 */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        TMinusOpr tminusoprNode2;
        PExp pexpNode3;
        PExp pexpNode4;
        tminusoprNode2 = (TMinusOpr)nodeArrayList2.get(0);
        pexpNode3 = (PExp)nodeArrayList1.get(0);
        pexpNode4 = (PExp)nodeArrayList3.get(0);

        pexpNode1 = new AMinusOprExp(tminusoprNode2, pexpNode3, pexpNode4);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new50() /* reduce ASingleExp4 */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        pexpNode1 = (PExp)nodeArrayList1.get(0);
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new51() /* reduce AMultiplyOprExp5 */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        TMultiplyOpr tmultiplyoprNode2;
        PExp pexpNode3;
        PExp pexpNode4;
        tmultiplyoprNode2 = (TMultiplyOpr)nodeArrayList2.get(0);
        pexpNode3 = (PExp)nodeArrayList1.get(0);
        pexpNode4 = (PExp)nodeArrayList3.get(0);

        pexpNode1 = new AMultiplyOprExp(tmultiplyoprNode2, pexpNode3, pexpNode4);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new52() /* reduce ADivideOprExp5 */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        TDivideOpr tdivideoprNode2;
        PExp pexpNode3;
        PExp pexpNode4;
        tdivideoprNode2 = (TDivideOpr)nodeArrayList2.get(0);
        pexpNode3 = (PExp)nodeArrayList1.get(0);
        pexpNode4 = (PExp)nodeArrayList3.get(0);

        pexpNode1 = new ADivideOprExp(tdivideoprNode2, pexpNode3, pexpNode4);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new53() /* reduce ASingleExp5 */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        pexpNode1 = (PExp)nodeArrayList1.get(0);
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new54() /* reduce AIntLtTerm */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        TIntLt tintltNode2;
        tintltNode2 = (TIntLt)nodeArrayList1.get(0);

        pexpNode1 = new AIntLtExp(tintltNode2);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new55() /* reduce ARealLtTerm */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        TRealLt trealltNode2;
        trealltNode2 = (TRealLt)nodeArrayList1.get(0);

        pexpNode1 = new ARealLtExp(trealltNode2);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new56() /* reduce ATrueLtTerm */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        TTrue ttrueNode2;
        ttrueNode2 = (TTrue)nodeArrayList1.get(0);

        pexpNode1 = new ATrueLtExp(ttrueNode2);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new57() /* reduce AFalseLtTerm */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        TFalse tfalseNode2;
        tfalseNode2 = (TFalse)nodeArrayList1.get(0);

        pexpNode1 = new AFalseLtExp(tfalseNode2);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new58() /* reduce AVarTerm */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        TId tidNode2;
        tidNode2 = (TId)nodeArrayList1.get(0);

        pexpNode1 = new AVarExp(tidNode2);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new59() /* reduce AThisTerm */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        TThis tthisNode2;
        tthisNode2 = (TThis)nodeArrayList1.get(0);

        pexpNode1 = new AThisExp(tthisNode2);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new60() /* reduce ASubExpTerm */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        pexpNode1 = (PExp)nodeArrayList2.get(0);
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new61() /* reduce AArraySubTerm */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        PExp pexpNode2;
        PExp pexpNode3;
        TLSq tlsqNode4;
        TRSq trsqNode5;
        pexpNode2 = (PExp)nodeArrayList1.get(0);
        pexpNode3 = (PExp)nodeArrayList3.get(0);
        tlsqNode4 = (TLSq)nodeArrayList2.get(0);
        trsqNode5 = (TRSq)nodeArrayList4.get(0);

        pexpNode1 = new AArraySubExp(pexpNode2, pexpNode3, tlsqNode4, trsqNode5);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new62() /* reduce AArrayLengthTerm */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        PExp pexpNode2;
        TLength tlengthNode3;
        pexpNode2 = (PExp)nodeArrayList1.get(0);
        tlengthNode3 = (TLength)nodeArrayList3.get(0);

        pexpNode1 = new AArrayLengthExp(pexpNode2, tlengthNode3);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new63() /* reduce AAmemfuncterm1Term */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        PExp pexpNode2;
        TId tidNode3;
        LinkedList listNode4 = new LinkedList();
        TPoint tpointNode5;
        pexpNode2 = (PExp)nodeArrayList1.get(0);
        tidNode3 = (TId)nodeArrayList3.get(0);
        {
            // Block
        }
        tpointNode5 = (TPoint)nodeArrayList2.get(0);

        pexpNode1 = new AMemFuncExp(pexpNode2, tidNode3, listNode4, tpointNode5);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new64() /* reduce AAmemfuncterm2Term */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        PExp pexpNode2;
        TId tidNode3;
        LinkedList listNode5 = new LinkedList();
        TPoint tpointNode6;
        pexpNode2 = (PExp)nodeArrayList1.get(0);
        tidNode3 = (TId)nodeArrayList3.get(0);
        {
            // Block
        LinkedList listNode4 = new LinkedList();
        listNode4 = (LinkedList)nodeArrayList5.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }
        tpointNode6 = (TPoint)nodeArrayList2.get(0);

        pexpNode1 = new AMemFuncExp(pexpNode2, tidNode3, listNode5, tpointNode6);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new65() /* reduce ANewIntArTerm */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        PExp pexpNode2;
        TNew tnewNode3;
        pexpNode2 = (PExp)nodeArrayList4.get(0);
        tnewNode3 = (TNew)nodeArrayList1.get(0);

        pexpNode1 = new ANewIntArExp(pexpNode2, tnewNode3);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new66() /* reduce ANewRealArTerm */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        PExp pexpNode2;
        TNew tnewNode3;
        pexpNode2 = (PExp)nodeArrayList4.get(0);
        tnewNode3 = (TNew)nodeArrayList1.get(0);

        pexpNode1 = new ANewRealArExp(pexpNode2, tnewNode3);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new67() /* reduce ANewObjectTerm */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        TId tidNode2;
        TNew tnewNode3;
        tidNode2 = (TId)nodeArrayList2.get(0);
        tnewNode3 = (TNew)nodeArrayList1.get(0);

        pexpNode1 = new ANewObjectExp(tidNode2, tnewNode3);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new68() /* reduce ACommaSepExpList */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        PExp pexpNode1;
        LinkedList listNode2 = new LinkedList();
        pexpNode1 = (PExp)nodeArrayList1.get(0);
        listNode2 = (LinkedList)nodeArrayList3.get(0);
	if(pexpNode1 != null)
	{
	  listNode3.add(pexpNode1);
	}
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new69() /* reduce ASingleExpList */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode2 = new LinkedList();
        {
            // Block
        PExp pexpNode1;
        pexpNode1 = (PExp)nodeArrayList1.get(0);
	if(pexpNode1 != null)
	{
	  listNode2.add(pexpNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new70() /* reduce ATerminal$ClassDecl */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode2 = new LinkedList();
        {
            // Block
        PClassDecl pclassdeclNode1;
        pclassdeclNode1 = (PClassDecl)nodeArrayList1.get(0);
	if(pclassdeclNode1 != null)
	{
	  listNode2.add(pclassdeclNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new71() /* reduce ANonTerminal$ClassDecl */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        LinkedList listNode1 = new LinkedList();
        PClassDecl pclassdeclNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        pclassdeclNode2 = (PClassDecl)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pclassdeclNode2 != null)
	{
	  listNode3.add(pclassdeclNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new72() /* reduce ATerminal$VarDecl */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode2 = new LinkedList();
        {
            // Block
        PVarDecl pvardeclNode1;
        pvardeclNode1 = (PVarDecl)nodeArrayList1.get(0);
	if(pvardeclNode1 != null)
	{
	  listNode2.add(pvardeclNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new73() /* reduce ANonTerminal$VarDecl */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        LinkedList listNode1 = new LinkedList();
        PVarDecl pvardeclNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        pvardeclNode2 = (PVarDecl)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pvardeclNode2 != null)
	{
	  listNode3.add(pvardeclNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new74() /* reduce ATerminal$MethodDecl */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode2 = new LinkedList();
        {
            // Block
        PMethodDecl pmethoddeclNode1;
        pmethoddeclNode1 = (PMethodDecl)nodeArrayList1.get(0);
	if(pmethoddeclNode1 != null)
	{
	  listNode2.add(pmethoddeclNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new75() /* reduce ANonTerminal$MethodDecl */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        LinkedList listNode1 = new LinkedList();
        PMethodDecl pmethoddeclNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        pmethoddeclNode2 = (PMethodDecl)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pmethoddeclNode2 != null)
	{
	  listNode3.add(pmethoddeclNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new76() /* reduce ATerminal$FormalRest */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode2 = new LinkedList();
        {
            // Block
        PArg pargNode1;
        pargNode1 = (PArg)nodeArrayList1.get(0);
	if(pargNode1 != null)
	{
	  listNode2.add(pargNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new77() /* reduce ANonTerminal$FormalRest */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        LinkedList listNode1 = new LinkedList();
        PArg pargNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        pargNode2 = (PArg)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pargNode2 != null)
	{
	  listNode3.add(pargNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new78() /* reduce ATerminal$State */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode2 = new LinkedList();
        {
            // Block
        PState pstateNode1;
        pstateNode1 = (PState)nodeArrayList1.get(0);
	if(pstateNode1 != null)
	{
	  listNode2.add(pstateNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new79() /* reduce ANonTerminal$State */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        LinkedList listNode1 = new LinkedList();
        PState pstateNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        pstateNode2 = (PState)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pstateNode2 != null)
	{
	  listNode3.add(pstateNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    private static int[][][] actionTable;
/*      {
			{{-1, REDUCE, 20}, {0, SHIFT, 1}, {2, SHIFT, 2}, {3, SHIFT, 3}, {4, SHIFT, 4}, {7, SHIFT, 5}, {15, SHIFT, 6}, {20, SHIFT, 7}, {21, SHIFT, 8}, {35, SHIFT, 9}, },
			{{-1, ERROR, 1}, {39, SHIFT, 18}, },
			{{-1, ERROR, 2}, {39, SHIFT, 19}, },
			{{-1, REDUCE, 28}, {37, SHIFT, 20}, },
			{{-1, REDUCE, 29}, {37, SHIFT, 21}, },
			{{-1, ERROR, 5}, {21, SHIFT, 22}, },
			{{-1, REDUCE, 27}, },
			{{-1, ERROR, 7}, {39, SHIFT, 23}, },
			{{-1, REDUCE, 30}, {34, SHIFT, 24}, {37, SHIFT, 25}, },
			{{-1, ERROR, 9}, {0, SHIFT, 1}, {2, SHIFT, 2}, {20, SHIFT, 7}, {21, SHIFT, 27}, {35, SHIFT, 9}, {36, SHIFT, 28}, },
			{{-1, ERROR, 10}, {44, ACCEPT, -1}, },
			{{-1, REDUCE, 0}, {7, SHIFT, 30}, },
			{{-1, REDUCE, 2}, },
			{{-1, REDUCE, 72}, },
			{{-1, ERROR, 14}, {21, SHIFT, 33}, },
			{{-1, REDUCE, 78}, },
			{{-1, REDUCE, 21}, {0, SHIFT, 1}, {2, SHIFT, 2}, {3, SHIFT, 3}, {4, SHIFT, 4}, {15, SHIFT, 6}, {20, SHIFT, 7}, {21, SHIFT, 8}, {35, SHIFT, 9}, },
			{{-1, REDUCE, 22}, {0, SHIFT, 1}, {2, SHIFT, 2}, {20, SHIFT, 7}, {21, SHIFT, 27}, {35, SHIFT, 9}, },
			{{-1, ERROR, 18}, {13, SHIFT, 37}, {14, SHIFT, 38}, {18, SHIFT, 39}, {19, SHIFT, 40}, {21, SHIFT, 41}, {23, SHIFT, 42}, {24, SHIFT, 43}, {33, SHIFT, 44}, {39, SHIFT, 45}, },
			{{-1, ERROR, 19}, {13, SHIFT, 37}, {14, SHIFT, 38}, {18, SHIFT, 39}, {19, SHIFT, 40}, {21, SHIFT, 41}, {23, SHIFT, 42}, {24, SHIFT, 43}, {33, SHIFT, 44}, {39, SHIFT, 45}, },
			{{-1, ERROR, 20}, {38, SHIFT, 54}, },
			{{-1, ERROR, 21}, {38, SHIFT, 55}, },
			{{-1, ERROR, 22}, {35, SHIFT, 56}, },
			{{-1, ERROR, 23}, {13, SHIFT, 37}, {14, SHIFT, 38}, {18, SHIFT, 39}, {19, SHIFT, 40}, {21, SHIFT, 41}, {23, SHIFT, 42}, {24, SHIFT, 43}, {33, SHIFT, 44}, {39, SHIFT, 45}, },
			{{-1, ERROR, 24}, {13, SHIFT, 37}, {14, SHIFT, 38}, {18, SHIFT, 39}, {19, SHIFT, 40}, {21, SHIFT, 41}, {23, SHIFT, 42}, {24, SHIFT, 43}, {33, SHIFT, 44}, {39, SHIFT, 45}, },
			{{-1, ERROR, 25}, {13, SHIFT, 37}, {14, SHIFT, 38}, {18, SHIFT, 39}, {19, SHIFT, 40}, {21, SHIFT, 41}, {23, SHIFT, 42}, {24, SHIFT, 43}, {33, SHIFT, 44}, {39, SHIFT, 45}, },
			{{-1, ERROR, 26}, {34, SHIFT, 60}, },
			{{-1, ERROR, 27}, {34, SHIFT, 24}, {37, SHIFT, 25}, },
			{{-1, REDUCE, 31}, },
			{{-1, ERROR, 29}, {0, SHIFT, 1}, {2, SHIFT, 2}, {20, SHIFT, 7}, {21, SHIFT, 27}, {35, SHIFT, 9}, {36, SHIFT, 61}, },
			{{-1, ERROR, 30}, {21, SHIFT, 62}, },
			{{-1, REDUCE, 70}, },
			{{-1, REDUCE, 1}, {7, SHIFT, 30}, },
			{{-1, ERROR, 33}, {41, SHIFT, 64}, },
			{{-1, REDUCE, 73}, },
			{{-1, REDUCE, 23}, {0, SHIFT, 1}, {2, SHIFT, 2}, {20, SHIFT, 7}, {21, SHIFT, 27}, {35, SHIFT, 9}, },
			{{-1, REDUCE, 79}, },
			{{-1, ERROR, 37}, {3, SHIFT, 65}, {4, SHIFT, 66}, {21, SHIFT, 67}, },
			{{-1, REDUCE, 59}, },
			{{-1, REDUCE, 56}, },
			{{-1, REDUCE, 57}, },
			{{-1, REDUCE, 58}, },
			{{-1, REDUCE, 55}, },
			{{-1, REDUCE, 54}, },
			{{-1, ERROR, 44}, {13, SHIFT, 37}, {14, SHIFT, 38}, {18, SHIFT, 39}, {19, SHIFT, 40}, {21, SHIFT, 41}, {23, SHIFT, 42}, {24, SHIFT, 43}, {33, SHIFT, 44}, {39, SHIFT, 45}, },
			{{-1, ERROR, 45}, {13, SHIFT, 37}, {14, SHIFT, 38}, {18, SHIFT, 39}, {19, SHIFT, 40}, {21, SHIFT, 41}, {23, SHIFT, 42}, {24, SHIFT, 43}, {33, SHIFT, 44}, {39, SHIFT, 45}, },
			{{-1, ERROR, 46}, {32, SHIFT, 70}, {40, SHIFT, 71}, },
			{{-1, REDUCE, 40}, {31, SHIFT, 72}, },
			{{-1, REDUCE, 42}, },
			{{-1, REDUCE, 44}, {29, SHIFT, 73}, {30, SHIFT, 74}, },
			{{-1, REDUCE, 47}, {27, SHIFT, 75}, {28, SHIFT, 76}, },
			{{-1, REDUCE, 50}, {25, SHIFT, 77}, {26, SHIFT, 78}, },
			{{-1, REDUCE, 53}, {22, SHIFT, 79}, {37, SHIFT, 80}, },
			{{-1, ERROR, 53}, {32, SHIFT, 70}, {40, SHIFT, 81}, },
			{{-1, REDUCE, 25}, },
			{{-1, REDUCE, 26}, },
			{{-1, ERROR, 56}, {9, SHIFT, 82}, },
			{{-1, ERROR, 57}, {32, SHIFT, 70}, {40, SHIFT, 83}, },
			{{-1, ERROR, 58}, {32, SHIFT, 70}, {41, SHIFT, 84}, },
			{{-1, ERROR, 59}, {32, SHIFT, 70}, {38, SHIFT, 85}, },
			{{-1, ERROR, 60}, {13, SHIFT, 37}, {14, SHIFT, 38}, {18, SHIFT, 39}, {19, SHIFT, 40}, {21, SHIFT, 41}, {23, SHIFT, 42}, {24, SHIFT, 43}, {33, SHIFT, 44}, {39, SHIFT, 45}, },
			{{-1, REDUCE, 32}, },
			{{-1, ERROR, 62}, {8, SHIFT, 87}, {35, SHIFT, 88}, },
			{{-1, REDUCE, 71}, },
			{{-1, REDUCE, 24}, },
			{{-1, ERROR, 65}, {37, SHIFT, 90}, },
			{{-1, ERROR, 66}, {37, SHIFT, 91}, },
			{{-1, ERROR, 67}, {39, SHIFT, 92}, },
			{{-1, REDUCE, 43}, },
			{{-1, ERROR, 69}, {32, SHIFT, 70}, {40, SHIFT, 93}, },
			{{-1, ERROR, 70}, {13, SHIFT, 37}, {14, SHIFT, 38}, {18, SHIFT, 39}, {19, SHIFT, 40}, {21, SHIFT, 41}, {23, SHIFT, 42}, {24, SHIFT, 43}, {33, SHIFT, 44}, {39, SHIFT, 45}, },
			{{-1, ERROR, 71}, {0, SHIFT, 1}, {2, SHIFT, 2}, {20, SHIFT, 7}, {21, SHIFT, 27}, {35, SHIFT, 9}, },
			{{-1, ERROR, 72}, {13, SHIFT, 37}, {14, SHIFT, 38}, {18, SHIFT, 39}, {19, SHIFT, 40}, {21, SHIFT, 41}, {23, SHIFT, 42}, {24, SHIFT, 43}, {33, SHIFT, 44}, {39, SHIFT, 45}, },
			{{-1, ERROR, 73}, {13, SHIFT, 37}, {14, SHIFT, 38}, {18, SHIFT, 39}, {19, SHIFT, 40}, {21, SHIFT, 41}, {23, SHIFT, 42}, {24, SHIFT, 43}, {39, SHIFT, 45}, },
			{{-1, ERROR, 74}, {13, SHIFT, 37}, {14, SHIFT, 38}, {18, SHIFT, 39}, {19, SHIFT, 40}, {21, SHIFT, 41}, {23, SHIFT, 42}, {24, SHIFT, 43}, {39, SHIFT, 45}, },
			{{-1, ERROR, 75}, {13, SHIFT, 37}, {14, SHIFT, 38}, {18, SHIFT, 39}, {19, SHIFT, 40}, {21, SHIFT, 41}, {23, SHIFT, 42}, {24, SHIFT, 43}, {39, SHIFT, 45}, },
			{{-1, ERROR, 76}, {13, SHIFT, 37}, {14, SHIFT, 38}, {18, SHIFT, 39}, {19, SHIFT, 40}, {21, SHIFT, 41}, {23, SHIFT, 42}, {24, SHIFT, 43}, {39, SHIFT, 45}, },
			{{-1, ERROR, 77}, {13, SHIFT, 37}, {14, SHIFT, 38}, {18, SHIFT, 39}, {19, SHIFT, 40}, {21, SHIFT, 41}, {23, SHIFT, 42}, {24, SHIFT, 43}, {39, SHIFT, 45}, },
			{{-1, ERROR, 78}, {13, SHIFT, 37}, {14, SHIFT, 38}, {18, SHIFT, 39}, {19, SHIFT, 40}, {21, SHIFT, 41}, {23, SHIFT, 42}, {24, SHIFT, 43}, {39, SHIFT, 45}, },
			{{-1, ERROR, 79}, {17, SHIFT, 103}, {21, SHIFT, 104}, },
			{{-1, ERROR, 80}, {13, SHIFT, 37}, {14, SHIFT, 38}, {18, SHIFT, 39}, {19, SHIFT, 40}, {21, SHIFT, 41}, {23, SHIFT, 42}, {24, SHIFT, 43}, {33, SHIFT, 44}, {39, SHIFT, 45}, },
			{{-1, ERROR, 81}, {0, SHIFT, 1}, {2, SHIFT, 2}, {20, SHIFT, 7}, {21, SHIFT, 27}, {35, SHIFT, 9}, },
			{{-1, ERROR, 82}, {10, SHIFT, 107}, },
			{{-1, ERROR, 83}, {41, SHIFT, 108}, },
			{{-1, REDUCE, 36}, },
			{{-1, REDUCE, 38}, },
			{{-1, ERROR, 86}, {32, SHIFT, 70}, {41, SHIFT, 109}, },
			{{-1, ERROR, 87}, {21, SHIFT, 110}, },
			{{-1, ERROR, 88}, {3, SHIFT, 3}, {4, SHIFT, 4}, {9, SHIFT, 111}, {15, SHIFT, 6}, {21, SHIFT, 112}, {36, SHIFT, 113}, },
			{{-1, ERROR, 89}, {35, SHIFT, 117}, },
			{{-1, ERROR, 90}, {13, SHIFT, 37}, {14, SHIFT, 38}, {18, SHIFT, 39}, {19, SHIFT, 40}, {21, SHIFT, 41}, {23, SHIFT, 42}, {24, SHIFT, 43}, {33, SHIFT, 44}, {39, SHIFT, 45}, },
			{{-1, ERROR, 91}, {13, SHIFT, 37}, {14, SHIFT, 38}, {18, SHIFT, 39}, {19, SHIFT, 40}, {21, SHIFT, 41}, {23, SHIFT, 42}, {24, SHIFT, 43}, {33, SHIFT, 44}, {39, SHIFT, 45}, },
			{{-1, ERROR, 92}, {40, SHIFT, 120}, },
			{{-1, REDUCE, 60}, },
			{{-1, REDUCE, 39}, {31, SHIFT, 72}, },
			{{-1, ERROR, 95}, {1, SHIFT, 121}, },
			{{-1, REDUCE, 41}, },
			{{-1, REDUCE, 45}, {27, SHIFT, 75}, {28, SHIFT, 76}, },
			{{-1, REDUCE, 46}, {27, SHIFT, 75}, {28, SHIFT, 76}, },
			{{-1, REDUCE, 48}, {25, SHIFT, 77}, {26, SHIFT, 78}, },
			{{-1, REDUCE, 49}, {25, SHIFT, 77}, {26, SHIFT, 78}, },
			{{-1, REDUCE, 51}, {22, SHIFT, 79}, {37, SHIFT, 80}, },
			{{-1, REDUCE, 52}, {22, SHIFT, 79}, {37, SHIFT, 80}, },
			{{-1, REDUCE, 62}, },
			{{-1, ERROR, 104}, {39, SHIFT, 122}, },
			{{-1, ERROR, 105}, {32, SHIFT, 70}, {38, SHIFT, 123}, },
			{{-1, REDUCE, 34}, },
			{{-1, ERROR, 107}, {11, SHIFT, 124}, },
			{{-1, REDUCE, 35}, },
			{{-1, REDUCE, 37}, },
			{{-1, REDUCE, 12}, },
			{{-1, ERROR, 111}, {3, SHIFT, 3}, {4, SHIFT, 4}, {15, SHIFT, 6}, {21, SHIFT, 112}, },
			{{-1, REDUCE, 30}, },
			{{-1, REDUCE, 4}, },
			{{-1, REDUCE, 74}, },
			{{-1, ERROR, 115}, {3, SHIFT, 3}, {4, SHIFT, 4}, {9, SHIFT, 111}, {15, SHIFT, 6}, {21, SHIFT, 112}, {36, SHIFT, 126}, },
			{{-1, ERROR, 116}, {9, SHIFT, 111}, {36, SHIFT, 128}, },
			{{-1, ERROR, 117}, {3, SHIFT, 3}, {4, SHIFT, 4}, {9, SHIFT, 111}, {15, SHIFT, 6}, {21, SHIFT, 112}, {36, SHIFT, 130}, },
			{{-1, ERROR, 118}, {32, SHIFT, 70}, {38, SHIFT, 133}, },
			{{-1, ERROR, 119}, {32, SHIFT, 70}, {38, SHIFT, 134}, },
			{{-1, REDUCE, 67}, },
			{{-1, ERROR, 121}, {0, SHIFT, 1}, {2, SHIFT, 2}, {20, SHIFT, 7}, {21, SHIFT, 27}, {35, SHIFT, 9}, },
			{{-1, ERROR, 122}, {13, SHIFT, 37}, {14, SHIFT, 38}, {18, SHIFT, 39}, {19, SHIFT, 40}, {21, SHIFT, 41}, {23, SHIFT, 42}, {24, SHIFT, 43}, {33, SHIFT, 44}, {39, SHIFT, 45}, {40, SHIFT, 136}, },
			{{-1, REDUCE, 61}, },
			{{-1, ERROR, 124}, {12, SHIFT, 139}, },
			{{-1, ERROR, 125}, {21, SHIFT, 140}, },
			{{-1, REDUCE, 6}, },
			{{-1, ERROR, 127}, {9, SHIFT, 111}, {36, SHIFT, 141}, },
			{{-1, REDUCE, 8}, },
			{{-1, REDUCE, 75}, },
			{{-1, REDUCE, 5}, },
			{{-1, ERROR, 131}, {3, SHIFT, 3}, {4, SHIFT, 4}, {9, SHIFT, 111}, {15, SHIFT, 6}, {21, SHIFT, 112}, {36, SHIFT, 142}, },
			{{-1, ERROR, 132}, {9, SHIFT, 111}, {36, SHIFT, 144}, },
			{{-1, REDUCE, 65}, },
			{{-1, REDUCE, 66}, },
			{{-1, REDUCE, 33}, },
			{{-1, REDUCE, 63}, },
			{{-1, REDUCE, 69}, {32, SHIFT, 70}, {43, SHIFT, 145}, },
			{{-1, ERROR, 138}, {40, SHIFT, 146}, },
			{{-1, ERROR, 139}, {39, SHIFT, 147}, },
			{{-1, ERROR, 140}, {39, SHIFT, 148}, },
			{{-1, REDUCE, 10}, },
			{{-1, REDUCE, 7}, },
			{{-1, ERROR, 143}, {9, SHIFT, 111}, {36, SHIFT, 149}, },
			{{-1, REDUCE, 9}, },
			{{-1, ERROR, 145}, {13, SHIFT, 37}, {14, SHIFT, 38}, {18, SHIFT, 39}, {19, SHIFT, 40}, {21, SHIFT, 41}, {23, SHIFT, 42}, {24, SHIFT, 43}, {33, SHIFT, 44}, {39, SHIFT, 45}, },
			{{-1, REDUCE, 64}, },
			{{-1, ERROR, 147}, {40, SHIFT, 151}, },
			{{-1, ERROR, 148}, {3, SHIFT, 3}, {4, SHIFT, 4}, {15, SHIFT, 6}, {21, SHIFT, 112}, },
			{{-1, REDUCE, 11}, },
			{{-1, REDUCE, 68}, },
			{{-1, ERROR, 151}, {35, SHIFT, 155}, },
			{{-1, ERROR, 152}, {40, SHIFT, 156}, },
			{{-1, REDUCE, 14}, {43, SHIFT, 157}, },
			{{-1, ERROR, 154}, {21, SHIFT, 160}, },
			{{-1, REDUCE, 20}, {0, SHIFT, 1}, {2, SHIFT, 2}, {3, SHIFT, 3}, {4, SHIFT, 4}, {15, SHIFT, 6}, {20, SHIFT, 7}, {21, SHIFT, 8}, {35, SHIFT, 9}, },
			{{-1, ERROR, 156}, {35, SHIFT, 162}, },
			{{-1, ERROR, 157}, {3, SHIFT, 3}, {4, SHIFT, 4}, {15, SHIFT, 6}, {21, SHIFT, 112}, },
			{{-1, REDUCE, 76}, },
			{{-1, REDUCE, 15}, {43, SHIFT, 157}, },
			{{-1, REDUCE, 16}, },
			{{-1, ERROR, 161}, {36, SHIFT, 165}, },
			{{-1, ERROR, 162}, {5, SHIFT, 166}, },
			{{-1, ERROR, 163}, {21, SHIFT, 168}, },
			{{-1, REDUCE, 77}, },
			{{-1, ERROR, 165}, {36, SHIFT, 169}, },
			{{-1, ERROR, 166}, {42, SHIFT, 170}, },
			{{-1, ERROR, 167}, {6, SHIFT, 171}, },
			{{-1, REDUCE, 17}, },
			{{-1, REDUCE, 3}, },
			{{-1, ERROR, 170}, {13, SHIFT, 37}, {14, SHIFT, 38}, {18, SHIFT, 39}, {19, SHIFT, 40}, {21, SHIFT, 41}, {23, SHIFT, 42}, {24, SHIFT, 43}, {33, SHIFT, 44}, {39, SHIFT, 45}, },
			{{-1, ERROR, 171}, {42, SHIFT, 174}, },
			{{-1, REDUCE, 20}, {0, SHIFT, 1}, {2, SHIFT, 2}, {3, SHIFT, 3}, {4, SHIFT, 4}, {15, SHIFT, 6}, {20, SHIFT, 7}, {21, SHIFT, 8}, {35, SHIFT, 9}, },
			{{-1, ERROR, 173}, {32, SHIFT, 70}, {41, SHIFT, 176}, },
			{{-1, ERROR, 174}, {13, SHIFT, 37}, {14, SHIFT, 38}, {18, SHIFT, 39}, {19, SHIFT, 40}, {21, SHIFT, 41}, {23, SHIFT, 42}, {24, SHIFT, 43}, {33, SHIFT, 44}, {39, SHIFT, 45}, },
			{{-1, ERROR, 175}, {16, SHIFT, 178}, },
			{{-1, REDUCE, 18}, },
			{{-1, ERROR, 177}, {32, SHIFT, 70}, {41, SHIFT, 179}, },
			{{-1, ERROR, 178}, {13, SHIFT, 37}, {14, SHIFT, 38}, {18, SHIFT, 39}, {19, SHIFT, 40}, {21, SHIFT, 41}, {23, SHIFT, 42}, {24, SHIFT, 43}, {33, SHIFT, 44}, {39, SHIFT, 45}, },
			{{-1, REDUCE, 19}, },
			{{-1, ERROR, 180}, {32, SHIFT, 70}, {41, SHIFT, 181}, },
			{{-1, ERROR, 181}, {36, SHIFT, 182}, },
			{{-1, REDUCE, 13}, },
        };*/
    private static int[][][] gotoTable;
/*      {
			{{-1, 10}, },
			{{-1, 11}, },
			{{-1, 31}, {32, 63}, },
			{{-1, 89}, },
			{{-1, 114}, {116, 129}, {127, 129}, {132, 129}, {143, 129}, },
			{{-1, 152}, },
			{{-1, 153}, },
			{{-1, 158}, {159, 164}, },
			{{-1, 167}, },
			{{-1, 172}, },
			{{-1, 12}, {155, 161}, {172, 175}, },
			{{-1, 13}, {16, 34}, {115, 34}, {131, 34}, },
			{{-1, 14}, {111, 125}, {148, 154}, {157, 163}, },
			{{-1, 15}, {17, 36}, {29, 36}, {35, 36}, {71, 95}, {81, 106}, {121, 135}, },
			{{-1, 26}, },
			{{-1, 137}, {18, 46}, {19, 53}, {23, 57}, {24, 58}, {25, 59}, {45, 69}, {60, 86}, {80, 105}, {90, 118}, {91, 119}, {170, 173}, {174, 177}, {178, 180}, },
			{{-1, 47}, {70, 94}, },
			{{-1, 48}, {44, 68}, {72, 96}, },
			{{-1, 49}, },
			{{-1, 50}, {73, 97}, {74, 98}, },
			{{-1, 51}, {75, 99}, {76, 100}, },
			{{-1, 52}, {77, 101}, {78, 102}, },
			{{-1, 138}, {145, 150}, },
			{{-1, 32}, },
			{{-1, 16}, {88, 115}, {117, 131}, },
			{{-1, 116}, {115, 127}, {117, 132}, {131, 143}, },
			{{-1, 159}, },
			{{-1, 17}, {9, 29}, {16, 35}, },
        };*/
    private static String[] errorMessages;
/*      {
			"expecting: 'if', 'while', 'int', 'real', 'class', 'boolean', print, id, '{', EOF",
			"expecting: '('",
			"expecting: id, '['",
			"expecting: id",
			"expecting: id, '=', '['",
			"expecting: 'if', 'while', print, id, '{', '}'",
			"expecting: EOF",
			"expecting: 'class', EOF",
			"expecting: 'if', 'while', 'int', 'real', 'public', 'boolean', 'return', print, id, '{', '}', EOF",
			"expecting: 'if', 'while', 'return', print, id, '{', '}', EOF",
			"expecting: 'if', 'while', 'int', 'real', 'boolean', 'return', print, id, '{', '}', EOF",
			"expecting: 'new', 'this', 'true', 'false', id, real lt, int lt, '!', '('",
			"expecting: ']'",
			"expecting: '{'",
			"expecting: '='",
			"expecting: '=', '['",
			"expecting: 'if', 'else', 'while', 'return', print, id, '{', '}', EOF",
			"expecting: ';'",
			"expecting: 'int', 'real', id",
			"expecting: '.', '*', '/', '+', '-', '>', '<', '&&', '||', '[', ']', ')', ';', ','",
			"expecting: '||', ')'",
			"expecting: '&&', '||', ']', ')', ';', ','",
			"expecting: '>', '<', '&&', '||', ']', ')', ';', ','",
			"expecting: '+', '-', '>', '<', '&&', '||', ']', ')', ';', ','",
			"expecting: '*', '/', '+', '-', '>', '<', '&&', '||', ']', ')', ';', ','",
			"expecting: 'public'",
			"expecting: '||', ';'",
			"expecting: '||', ']'",
			"expecting: 'extends', '{'",
			"expecting: '['",
			"expecting: 'if', 'while', print, id, '{'",
			"expecting: 'new', 'this', 'true', 'false', id, real lt, int lt, '('",
			"expecting: 'length', id",
			"expecting: 'static'",
			"expecting: 'int', 'real', 'public', 'boolean', id, '}'",
			"expecting: ')'",
			"expecting: 'else'",
			"expecting: 'void'",
			"expecting: 'int', 'real', 'boolean', id",
			"expecting: 'public', '}'",
			"expecting: 'new', 'this', 'true', 'false', id, real lt, int lt, '!', '(', ')'",
			"expecting: 'main'",
			"expecting: '||', ')', ','",
			"expecting: ')', ','",
			"expecting: 'if', 'while', 'int', 'real', 'boolean', print, id, '{', '}'",
			"expecting: '}'",
			"expecting: 'pre'",
			"expecting: ':'",
			"expecting: 'post'",
			"expecting: 'if', 'while', 'int', 'real', 'boolean', 'return', print, id, '{'",
			"expecting: 'return'",
        };*/
    private static int[] errors;
/*      {
			0, 1, 1, 2, 2, 3, 3, 1, 4, 5, 6, 7, 6, 8, 3, 9, 10, 9, 11, 11, 12, 12, 13, 11, 11, 11, 14, 15, 16, 5, 3, 7, 7, 17, 8, 9, 9, 18, 19, 19, 19, 19, 19, 19, 11, 11, 20, 21, 21, 22, 23, 24, 19, 20, 3, 3, 25, 20, 26, 27, 11, 16, 28, 7, 8, 29, 29, 1, 21, 20, 11, 30, 11, 31, 31, 31, 31, 31, 31, 32, 11, 30, 33, 17, 16, 14, 26, 3, 34, 13, 11, 11, 35, 19, 21, 36, 21, 23, 23, 24, 24, 19, 19, 19, 1, 27, 16, 37, 16, 16, 13, 38, 3, 7, 39, 34, 39, 34, 27, 27, 19, 30, 40, 19, 41, 3, 7, 39, 7, 39, 7, 34, 39, 19, 19, 16, 19, 42, 35, 1, 1, 7, 7, 39, 7, 11, 19, 35, 38, 7, 35, 13, 35, 43, 3, 44, 13, 38, 43, 43, 43, 45, 46, 3, 43, 45, 47, 48, 43, 7, 11, 47, 49, 26, 11, 50, 48, 26, 11, 49, 26, 45, 39, 
        };*/

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Parser.class.getResourceAsStream("parser.dat")));

            // read actionTable
            int length = s.readInt();
            Parser.actionTable = new int[length][][];
            for(int i = 0; i < Parser.actionTable.length; i++)
            {
                length = s.readInt();
                Parser.actionTable[i] = new int[length][3];
                for(int j = 0; j < Parser.actionTable[i].length; j++)
                {
                for(int k = 0; k < 3; k++)
                {
                    Parser.actionTable[i][j][k] = s.readInt();
                }
                }
            }

            // read gotoTable
            length = s.readInt();
            gotoTable = new int[length][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][2];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                for(int k = 0; k < 2; k++)
                {
                    gotoTable[i][j][k] = s.readInt();
                }
                }
            }

            // read errorMessages
            length = s.readInt();
            errorMessages = new String[length];
            for(int i = 0; i < errorMessages.length; i++)
            {
                length = s.readInt();
                StringBuffer buffer = new StringBuffer();

                for(int j = 0; j < length; j++)
                {
                buffer.append(s.readChar());
                }
                errorMessages[i] = buffer.toString();
            }

            // read errors
            length = s.readInt();
            errors = new int[length];
            for(int i = 0; i < errors.length; i++)
            {
                errors[i] = s.readInt();
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"parser.dat\" is either missing or corrupted.");
        }
    }
}
