/* This file was generated by SableCC (http://www.sablecc.org/). */

package xyzlex.parser;

import xyzlex.node.*;
import xyzlex.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTIf(@SuppressWarnings("unused") TIf node)
    {
        this.index = 0;
    }

    @Override
    public void caseTElse(@SuppressWarnings("unused") TElse node)
    {
        this.index = 1;
    }

    @Override
    public void caseTWhile(@SuppressWarnings("unused") TWhile node)
    {
        this.index = 2;
    }

    @Override
    public void caseTInt(@SuppressWarnings("unused") TInt node)
    {
        this.index = 3;
    }

    @Override
    public void caseTReal(@SuppressWarnings("unused") TReal node)
    {
        this.index = 4;
    }

    @Override
    public void caseTPre(@SuppressWarnings("unused") TPre node)
    {
        this.index = 5;
    }

    @Override
    public void caseTPost(@SuppressWarnings("unused") TPost node)
    {
        this.index = 6;
    }

    @Override
    public void caseTClass(@SuppressWarnings("unused") TClass node)
    {
        this.index = 7;
    }

    @Override
    public void caseTExtends(@SuppressWarnings("unused") TExtends node)
    {
        this.index = 8;
    }

    @Override
    public void caseTPublic(@SuppressWarnings("unused") TPublic node)
    {
        this.index = 9;
    }

    @Override
    public void caseTStatic(@SuppressWarnings("unused") TStatic node)
    {
        this.index = 10;
    }

    @Override
    public void caseTVoid(@SuppressWarnings("unused") TVoid node)
    {
        this.index = 11;
    }

    @Override
    public void caseTMain(@SuppressWarnings("unused") TMain node)
    {
        this.index = 12;
    }

    @Override
    public void caseTNew(@SuppressWarnings("unused") TNew node)
    {
        this.index = 13;
    }

    @Override
    public void caseTThis(@SuppressWarnings("unused") TThis node)
    {
        this.index = 14;
    }

    @Override
    public void caseTBoolean(@SuppressWarnings("unused") TBoolean node)
    {
        this.index = 15;
    }

    @Override
    public void caseTReturn(@SuppressWarnings("unused") TReturn node)
    {
        this.index = 16;
    }

    @Override
    public void caseTLength(@SuppressWarnings("unused") TLength node)
    {
        this.index = 17;
    }

    @Override
    public void caseTTrue(@SuppressWarnings("unused") TTrue node)
    {
        this.index = 18;
    }

    @Override
    public void caseTFalse(@SuppressWarnings("unused") TFalse node)
    {
        this.index = 19;
    }

    @Override
    public void caseTPrint(@SuppressWarnings("unused") TPrint node)
    {
        this.index = 20;
    }

    @Override
    public void caseTId(@SuppressWarnings("unused") TId node)
    {
        this.index = 21;
    }

    @Override
    public void caseTPoint(@SuppressWarnings("unused") TPoint node)
    {
        this.index = 22;
    }

    @Override
    public void caseTRealLt(@SuppressWarnings("unused") TRealLt node)
    {
        this.index = 23;
    }

    @Override
    public void caseTIntLt(@SuppressWarnings("unused") TIntLt node)
    {
        this.index = 24;
    }

    @Override
    public void caseTMultiplyOpr(@SuppressWarnings("unused") TMultiplyOpr node)
    {
        this.index = 25;
    }

    @Override
    public void caseTDivideOpr(@SuppressWarnings("unused") TDivideOpr node)
    {
        this.index = 26;
    }

    @Override
    public void caseTPlusOpr(@SuppressWarnings("unused") TPlusOpr node)
    {
        this.index = 27;
    }

    @Override
    public void caseTMinusOpr(@SuppressWarnings("unused") TMinusOpr node)
    {
        this.index = 28;
    }

    @Override
    public void caseTGreaterOpr(@SuppressWarnings("unused") TGreaterOpr node)
    {
        this.index = 29;
    }

    @Override
    public void caseTLessOpr(@SuppressWarnings("unused") TLessOpr node)
    {
        this.index = 30;
    }

    @Override
    public void caseTAndOpr(@SuppressWarnings("unused") TAndOpr node)
    {
        this.index = 31;
    }

    @Override
    public void caseTOrOpr(@SuppressWarnings("unused") TOrOpr node)
    {
        this.index = 32;
    }

    @Override
    public void caseTNotOpr(@SuppressWarnings("unused") TNotOpr node)
    {
        this.index = 33;
    }

    @Override
    public void caseTAssignOpr(@SuppressWarnings("unused") TAssignOpr node)
    {
        this.index = 34;
    }

    @Override
    public void caseTLB(@SuppressWarnings("unused") TLB node)
    {
        this.index = 35;
    }

    @Override
    public void caseTRB(@SuppressWarnings("unused") TRB node)
    {
        this.index = 36;
    }

    @Override
    public void caseTLSq(@SuppressWarnings("unused") TLSq node)
    {
        this.index = 37;
    }

    @Override
    public void caseTRSq(@SuppressWarnings("unused") TRSq node)
    {
        this.index = 38;
    }

    @Override
    public void caseTLP(@SuppressWarnings("unused") TLP node)
    {
        this.index = 39;
    }

    @Override
    public void caseTRP(@SuppressWarnings("unused") TRP node)
    {
        this.index = 40;
    }

    @Override
    public void caseTSemi(@SuppressWarnings("unused") TSemi node)
    {
        this.index = 41;
    }

    @Override
    public void caseTColon(@SuppressWarnings("unused") TColon node)
    {
        this.index = 42;
    }

    @Override
    public void caseTComma(@SuppressWarnings("unused") TComma node)
    {
        this.index = 43;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 44;
    }
}
