/* This file was generated by SableCC (http://www.sablecc.org/). */

package xyzlex.node;

import xyzlex.analysis.*;

@SuppressWarnings("nls")
public final class AAssignState extends PState
{
    private TId _id_;
    private PExp _index_;
    private PExp _value_;

    public AAssignState()
    {
        // Constructor
    }

    public AAssignState(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") PExp _index_,
        @SuppressWarnings("hiding") PExp _value_)
    {
        // Constructor
        setId(_id_);

        setIndex(_index_);

        setValue(_value_);

    }

    @Override
    public Object clone()
    {
        return new AAssignState(
            cloneNode(this._id_),
            cloneNode(this._index_),
            cloneNode(this._value_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAssignState(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public PExp getIndex()
    {
        return this._index_;
    }

    public void setIndex(PExp node)
    {
        if(this._index_ != null)
        {
            this._index_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._index_ = node;
    }

    public PExp getValue()
    {
        return this._value_;
    }

    public void setValue(PExp node)
    {
        if(this._value_ != null)
        {
            this._value_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._value_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._index_)
            + toString(this._value_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._index_ == child)
        {
            this._index_ = null;
            return;
        }

        if(this._value_ == child)
        {
            this._value_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._index_ == oldChild)
        {
            setIndex((PExp) newChild);
            return;
        }

        if(this._value_ == oldChild)
        {
            setValue((PExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
