/* This file was generated by SableCC (http://www.sablecc.org/). */

package xyzlex.node;

import xyzlex.analysis.*;

@SuppressWarnings("nls")
public final class AVarExp extends PExp
{
    private TId _var_;

    public AVarExp()
    {
        // Constructor
    }

    public AVarExp(
        @SuppressWarnings("hiding") TId _var_)
    {
        // Constructor
        setVar(_var_);

    }

    @Override
    public Object clone()
    {
        return new AVarExp(
            cloneNode(this._var_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVarExp(this);
    }

    public TId getVar()
    {
        return this._var_;
    }

    public void setVar(TId node)
    {
        if(this._var_ != null)
        {
            this._var_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._var_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._var_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._var_ == child)
        {
            this._var_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._var_ == oldChild)
        {
            setVar((TId) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
