/* This file was generated by SableCC (http://www.sablecc.org/). */

package xyzlex.node;

import java.util.*;
import xyzlex.analysis.*;

@SuppressWarnings("nls")
public final class ABlockState extends PState
{
    private final LinkedList<PState> _list_ = new LinkedList<PState>();

    public ABlockState()
    {
        // Constructor
    }

    public ABlockState(
        @SuppressWarnings("hiding") List<PState> _list_)
    {
        // Constructor
        setList(_list_);

    }

    @Override
    public Object clone()
    {
        return new ABlockState(
            cloneList(this._list_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABlockState(this);
    }

    public LinkedList<PState> getList()
    {
        return this._list_;
    }

    public void setList(List<PState> list)
    {
        this._list_.clear();
        this._list_.addAll(list);
        for(PState e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._list_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._list_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PState> i = this._list_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PState) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
