/* This file was generated by SableCC (http://www.sablecc.org/). */

package xyzlex.node;

import xyzlex.analysis.*;

@SuppressWarnings("nls")
public final class AIntLtExp extends PExp
{
    private TIntLt _intLt_;

    public AIntLtExp()
    {
        // Constructor
    }

    public AIntLtExp(
        @SuppressWarnings("hiding") TIntLt _intLt_)
    {
        // Constructor
        setIntLt(_intLt_);

    }

    @Override
    public Object clone()
    {
        return new AIntLtExp(
            cloneNode(this._intLt_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIntLtExp(this);
    }

    public TIntLt getIntLt()
    {
        return this._intLt_;
    }

    public void setIntLt(TIntLt node)
    {
        if(this._intLt_ != null)
        {
            this._intLt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._intLt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._intLt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._intLt_ == child)
        {
            this._intLt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._intLt_ == oldChild)
        {
            setIntLt((TIntLt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
